# Generated by Django 5.2.7 on 2025-10-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apepaterno', models.CharField(max_length=50)),
                ('apematerno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('alergias', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
